/**
 * Google reCAPTCHA Verification Service.
 * * This service provides a security layer to distinguish human users from automated bots.
 * It communicates with Google's Siteverify API to validate tokens generated by 
 * the frontend reCAPTCHA widget.
 * * Key features:
 * - Environment-aware bypassing (Development vs. Production).
 * - Integration with Axios for robust HTTP communication.
 * - Secure secret handling via environment variables.
 * * @module services/CaptchaService
 * @requires axios
 * @author Nguyễn Huỳnh Thanh Tâm
 * @since 2026-03-27
 */

const axios = require('axios');

/**
 * Validates a reCAPTCHA response token with Google's servers.
 * @async
 * @param {string} token - The g-recaptcha-response token sent from the client.
 * @returns {Promise<boolean>} True if the token is valid or bypassed, false otherwise.
 */
const verifyGoogleCaptcha = async (token) => {
  // Bypass cho môi trường development để bạn đỡ phải click hình ảnh khi đang test
  if (process.env.NODE_ENV === 'development' || token === 'bypass-captcha') {
    return true;
  }

  try {
    const response = await axios.post(
      `https://www.google.com/recaptcha/api/siteverify?secret=${process.env.RECAPTCHA_SECRET}&response=${token}`
    );
    return response.data.success;
  } catch (error) {
    return false;
  }
};

module.exports = { verifyGoogleCaptcha };